Usadb.create!(base_country: "USA", base_state_abbr: "AL", base_state: "Alabama", base_tip: 0.164) 
Usadb.create!(base_country: "USA", base_state_abbr: "AK", base_state: "Alaska", base_tip: 0.17) 
Usadb.create!(base_country: "USA", base_state_abbr: "AZ", base_state: "Arizona", base_tip: 0.165) 
Usadb.create!(base_country: "USA", base_state_abbr: "AR", base_state: "Arkansas", base_tip: 0.169) 
Usadb.create!(base_country: "USA", base_state_abbr: "CA", base_state: "California", base_tip: 0.155)
Usadb.create!(base_country: "USA", base_state_abbr: "CO", base_state: "Colorado", base_tip: 0.165) 
Usadb.create!(base_country: "USA", base_state_abbr: "CT", base_state: "Connecticut", base_tip: 0.156)
Usadb.create!(base_country: "USA", base_state_abbr: "DE", base_state: "Delaware", base_tip: 0.14)
Usadb.create!(base_country: "USA", base_state_abbr: "FL", base_state: "Florida", base_tip: 0.162)
Usadb.create!(base_country: "USA", base_state_abbr: "GA", base_state: "Georgia", base_tip: 0.162) 
Usadb.create!(base_country: "USA", base_state_abbr: "HI", base_state: "Hawaii", base_tip: 0.151) 
Usadb.create!(base_country: "USA", base_state_abbr: "ID", base_state: "Idaho", base_tip: 0.165) 
Usadb.create!(base_country: "USA", base_state_abbr: "IL", base_state: "Illinois", base_tip: 0.165) 
Usadb.create!(base_country: "USA", base_state_abbr: "IN", base_state: "Indiana", base_tip: 0.164) 
Usadb.create!(base_country: "USA", base_state_abbr: "IA", base_state: "Iowa", base_tip: 0.161) 
Usadb.create!(base_country: "USA", base_state_abbr: "KS", base_state: "Kansas", base_tip: 0.162) 
Usadb.create!(base_country: "USA", base_state_abbr: "KY", base_state: "Kentucky", base_tip: 0.164) 
Usadb.create!(base_country: "USA", base_state_abbr: "LA", base_state: "Louisiana", base_tip: 0.161) 
Usadb.create!(base_country: "USA", base_state_abbr: "ME", base_state: "Maine", base_tip: 0.164) 
Usadb.create!(base_country: "USA", base_state_abbr: "MD", base_state: "Maryland", base_tip: 0.158) 
Usadb.create!(base_country: "USA", base_state_abbr: "MA", base_state: "Massachusetts", base_tip: 0.157) 
Usadb.create!(base_country: "USA", base_state_abbr: "MI", base_state: "Michigan", base_tip: 0.164) 
Usadb.create!(base_country: "USA", base_state_abbr: "MN", base_state: "Minnesota", base_tip: 0.157) 
Usadb.create!(base_country: "USA", base_state_abbr: "MS", base_state: "Mississippi", base_tip: 0.165) 
Usadb.create!(base_country: "USA", base_state_abbr: "MO", base_state: "Missouri", base_tip: 0.165) 
Usadb.create!(base_country: "USA", base_state_abbr: "MT", base_state: "Montana", base_tip: 0.16) 
Usadb.create!(base_country: "USA", base_state_abbr: "NE", base_state: "Nebraska", base_tip: 0.155) 
Usadb.create!(base_country: "USA", base_state_abbr: "NV", base_state: "Nevada", base_tip: 0.162) 
Usadb.create!(base_country: "USA", base_state_abbr: "NH", base_state: "New Hampshire", base_tip: 0.162) 
Usadb.create!(base_country: "USA", base_state_abbr: "NJ", base_state: "New Jersey", base_tip: 0.161) 
Usadb.create!(base_country: "USA", base_state_abbr: "NM", base_state: "New Mexico", base_tip: 0.166) 
Usadb.create!(base_country: "USA", base_state_abbr: "NY", base_state: "New York", base_tip: 0.158) 
Usadb.create!(base_country: "USA", base_state_abbr: "NC", base_state: "North Carolina", base_tip: 0.167) 
Usadb.create!(base_country: "USA", base_state_abbr: "ND", base_state: "North Dakota", base_tip: 0.156) 
Usadb.create!(base_country: "USA", base_state_abbr: "OH", base_state: "Ohio", base_tip: 0.161) 
Usadb.create!(base_country: "USA", base_state_abbr: "OK", base_state: "Oklahoma", base_tip: 0.162) 
Usadb.create!(base_country: "USA", base_state_abbr: "OR", base_state: "Oregon", base_tip: 0.157) 
Usadb.create!(base_country: "USA", base_state_abbr: "PA", base_state: "Pennsylvania", base_tip: 0.16) 
Usadb.create!(base_country: "USA", base_state_abbr: "RI", base_state: "Rhode Island", base_tip: 0.158) 
Usadb.create!(base_country: "USA", base_state_abbr: "SC", base_state: "South Carolina", base_tip: 0.167) 
Usadb.create!(base_country: "USA", base_state_abbr: "SD", base_state: "South Dakota", base_tip: 0.153) 
Usadb.create!(base_country: "USA", base_state_abbr: "TN", base_state: "Tennessee", base_tip: 0.163) 
Usadb.create!(base_country: "USA", base_state_abbr: "TX", base_state: "Texas", base_tip: 0.163) 
Usadb.create!(base_country: "USA", base_state_abbr: "UT", base_state: "Utah", base_tip: 0.161) 
Usadb.create!(base_country: "USA", base_state_abbr: "VT", base_state: "Vermont", base_tip: 0.155) 
Usadb.create!(base_country: "USA", base_state_abbr: "VA", base_state: "Virginia", base_tip: 0.16) 
Usadb.create!(base_country: "USA", base_state_abbr: "WA", base_state: "Washington", base_tip: 0.159) 
Usadb.create!(base_country: "USA", base_state_abbr: "WV", base_state: "West Virginia", base_tip: 0.167) 
Usadb.create!(base_country: "USA", base_state_abbr: "WI", base_state: "Wisconsin", base_tip: 0.159) 
Usadb.create!(base_country: "USA", base_state_abbr: "WY", base_state: "Wyoming", base_tip: 0.154) 

Service.create!(general_service: "Good Service", service_tip_overide: 0.20)
Service.create!(general_service: "Normal Service")	
Service.create!(general_service: "Poor Service", service_tip_overide: 0.10)
Service.create!(general_service: "Horrible Service",service_tip_overide: 0.1)

Intdb.create!(country_name: "AFGHANISTAN", curr_name: "Afghani", iso: "AFN")
Intdb.create!(country_name: "ÅLAND ISLANDS", curr_name: "Euro", iso: "EUR")
Intdb.create!(country_name: "ALBANIA", curr_name: "Lek", iso: "ALL")
Intdb.create!(country_name: "ALGERIA", curr_name: "Algerian Dinar", iso: "DZD")
Intdb.create!(country_name: "AMERICAN SAMOA", curr_name: "US Dollar", iso: "USD")
Intdb.create!(country_name: "ANDORRA", curr_name: "Euro", iso: "EUR")
Intdb.create!(country_name: "ANGOLA", curr_name: "Kwanza", iso: "AOA")
Intdb.create!(country_name: "ANGUILLA", curr_name: "East Caribbean Dollar", iso: "XCD")
Intdb.create!(country_name: "ANTARCTICA", curr_name: "No universal currency")
Intdb.create!(country_name: "ANTIGUA AND BARBUDA", curr_name: "East Caribbean Dollar", iso: "XCD")
Intdb.create!(country_name: "ARGENTINA", curr_name: "Argentine Peso", iso: "ARS")
Intdb.create!(country_name: "ARMENIA", curr_name: "Armenian Dram", iso: "AMD")
Intdb.create!(country_name: "ARUBA", curr_name: "Aruban Florin", iso: "AWG")
Intdb.create!(country_name: "AUSTRALIA", curr_name: "Australian Dollar", iso: "AUD")
Intdb.create!(country_name: "AUSTRIA", curr_name: "Euro", iso: "EUR")
Intdb.create!(country_name: "AZERBAIJAN", curr_name: "Azerbaijanian Manat", iso: "AZN")
Intdb.create!(country_name: "BAHAMAS (THE)", curr_name: "Bahamian Dollar", iso: "BSD")
Intdb.create!(country_name: "BAHRAIN", curr_name: "Bahraini Dinar", iso: "BHD")
Intdb.create!(country_name: "BANGLADESH", curr_name: "Taka", iso: "BDT")
Intdb.create!(country_name: "BARBADOS", curr_name: "Barbados Dollar", iso: "BBD")
Intdb.create!(country_name: "BELARUS", curr_name: "Belarusian Ruble", iso: "BYR")
Intdb.create!(country_name: "BELGIUM", curr_name: "Euro", iso: "EUR")
Intdb.create!(country_name: "BELIZE", curr_name: "Belize Dollar", iso: "BZD")
Intdb.create!(country_name: "BENIN", curr_name: "CFA Franc BCEAO", iso: "XOF")
Intdb.create!(country_name: "BERMUDA", curr_name: "Bermudian Dollar", iso: "BMD")
Intdb.create!(country_name: "BHUTAN", curr_name: "Indian Rupee", iso: "INR")
Intdb.create!(country_name: "BHUTAN", curr_name: "Ngultrum", iso: "BTN")
Intdb.create!(country_name: "BOLIVIA (PLURINATIONAL STATE OF)", curr_name: "Boliviano", iso: "BOB")
Intdb.create!(country_name: "BOLIVIA (PLURINATIONAL STATE OF)", curr_name: "Mvdol", iso: "BOV")
Intdb.create!(country_name: "BONAIRE, SINT EUSTATIUS AND SABA", curr_name: "US Dollar", iso: "USD")
Intdb.create!(country_name: "BOSNIA AND HERZEGOVINA", curr_name: "Convertible Mark", iso: "BAM")
Intdb.create!(country_name: "BOTSWANA", curr_name: "Pula", iso: "BWP")
Intdb.create!(country_name: "BOUVET ISLAND", curr_name: "Norwegian Krone", iso: "NOK")
Intdb.create!(country_name: "BRAZIL", curr_name: "Brazilian Real", iso: "BRL")
Intdb.create!(country_name: "BRITISH INDIAN OCEAN TERRITORY (THE)", curr_name: "US Dollar", iso: "USD")
Intdb.create!(country_name: "BRUNEI DARUSSALAM", curr_name: "Brunei Dollar", iso: "BND")
Intdb.create!(country_name: "BULGARIA", curr_name: "Bulgarian Lev", iso: "BGN")
Intdb.create!(country_name: "BURKINA FASO", curr_name: "CFA Franc BCEAO", iso: "XOF")
Intdb.create!(country_name: "BURUNDI", curr_name: "Burundi Franc", iso: "BIF")
Intdb.create!(country_name: "CABO VERDE", curr_name: "Cabo Verde Escudo", iso: "CVE")
Intdb.create!(country_name: "CAMBODIA", curr_name: "Riel", iso: "KHR")
Intdb.create!(country_name: "CAMEROON", curr_name: "CFA Franc BEAC", iso: "XAF")
Intdb.create!(country_name: "CANADA", curr_name: "Canadian Dollar", iso: "CAD")
Intdb.create!(country_name: "CAYMAN ISLANDS (THE)", curr_name: "Cayman Islands Dollar", iso: "KYD")
Intdb.create!(country_name: "CENTRAL AFRICAN REPUBLIC (THE)", curr_name: "CFA Franc BEAC", iso: "XAF")
Intdb.create!(country_name: "CHAD", curr_name: "CFA Franc BEAC", iso: "XAF")
Intdb.create!(country_name: "CHILE", curr_name: "Chilean Peso", iso: "CLP")
Intdb.create!(country_name: "CHILE", curr_name: "Unidad de Fomento", iso: "CLF")
Intdb.create!(country_name: "CHINA", curr_name: "Yuan Renminbi", iso: "CNY")
Intdb.create!(country_name: "CHRISTMAS ISLAND", curr_name: "Australian Dollar", iso: "AUD")
Intdb.create!(country_name: "COCOS (KEELING) ISLANDS (THE)", curr_name: "Australian Dollar", iso: "AUD")
Intdb.create!(country_name: "COLOMBIA", curr_name: "Colombian Peso", iso: "COP")
Intdb.create!(country_name: "COLOMBIA", curr_name: "Unidad de Valor Real", iso: "COU")
Intdb.create!(country_name: "COMOROS (THE)", curr_name: "Comoro Franc", iso: "KMF")
Intdb.create!(country_name: "CONGO (THE DEMOCRATIC REPUBLIC OF THE)", curr_name: "Congolese Franc", iso: "CDF")
Intdb.create!(country_name: "CONGO (THE)", curr_name: "CFA Franc BEAC", iso: "XAF")
Intdb.create!(country_name: "COOK ISLANDS (THE)", curr_name: "New Zealand Dollar", iso: "NZD")
Intdb.create!(country_name: "COSTA RICA", curr_name: "Costa Rican Colon", iso: "CRC")
Intdb.create!(country_name: "CÔTE D'IVOIRE", curr_name: "CFA Franc BCEAO", iso: "XOF")
Intdb.create!(country_name: "CROATIA", curr_name: "Kuna", iso: "HRK")
Intdb.create!(country_name: "CUBA", curr_name: "Cuban Peso", iso: "CUP")
Intdb.create!(country_name: "CUBA", curr_name: "Peso Convertible", iso: "CUC")
Intdb.create!(country_name: "CURAÇAO", curr_name: "Netherlands Antillean Guilder", iso: "ANG")
Intdb.create!(country_name: "CYPRUS", curr_name: "Euro", iso: "EUR")
Intdb.create!(country_name: "CZECH REPUBLIC (THE)", curr_name: "Czech Koruna", iso: "CZK")
Intdb.create!(country_name: "DENMARK", curr_name: "Danish Krone", iso: "DKK")
Intdb.create!(country_name: "DJIBOUTI", curr_name: "Djibouti Franc", iso: "DJF")
Intdb.create!(country_name: "DOMINICA", curr_name: "East Caribbean Dollar", iso: "XCD")
Intdb.create!(country_name: "DOMINICAN REPUBLIC (THE)", curr_name: "Dominican Peso", iso: "DOP")
Intdb.create!(country_name: "ECUADOR", curr_name: "US Dollar", iso: "USD")
Intdb.create!(country_name: "EGYPT", curr_name: "Egyptian Pound", iso: "EGP")
Intdb.create!(country_name: "EL SALVADOR", curr_name: "El Salvador Colon", iso: "SVC")
Intdb.create!(country_name: "EL SALVADOR", curr_name: "US Dollar", iso: "USD")
Intdb.create!(country_name: "EQUATORIAL GUINEA", curr_name: "CFA Franc BEAC", iso: "XAF")
Intdb.create!(country_name: "ERITREA", curr_name: "Nakfa", iso: "ERN")
Intdb.create!(country_name: "ESTONIA", curr_name: "Euro", iso: "EUR")
Intdb.create!(country_name: "ETHIOPIA", curr_name: "Ethiopian Birr", iso: "ETB")
Intdb.create!(country_name: "EUROPEAN UNION", curr_name: "Euro", iso: "EUR")
Intdb.create!(country_name: "FALKLAND ISLANDS (THE) [MALVINAS]", curr_name: "Falkland Islands Pound", iso: "FKP")
Intdb.create!(country_name: "FAROE ISLANDS (THE)", curr_name: "Danish Krone", iso: "DKK")
Intdb.create!(country_name: "FIJI", curr_name: "Fiji Dollar", iso: "FJD")
Intdb.create!(country_name: "FINLAND", curr_name: "Euro", iso: "EUR")
Intdb.create!(country_name: "FRANCE", curr_name: "Euro", iso: "EUR")
Intdb.create!(country_name: "FRENCH GUIANA", curr_name: "Euro", iso: "EUR")
Intdb.create!(country_name: "FRENCH POLYNESIA", curr_name: "CFP Franc", iso: "XPF")
Intdb.create!(country_name: "FRENCH SOUTHERN TERRITORIES (THE)", curr_name: "Euro", iso: "EUR")
Intdb.create!(country_name: "GABON", curr_name: "CFA Franc BEAC", iso: "XAF")
Intdb.create!(country_name: "GAMBIA (THE)", curr_name: "Dalasi", iso: "GMD")
Intdb.create!(country_name: "GEORGIA", curr_name: "Lari", iso: "GEL")
Intdb.create!(country_name: "GERMANY", curr_name: "Euro", iso: "EUR")
Intdb.create!(country_name: "GHANA", curr_name: "Ghana Cedi", iso: "GHS")
Intdb.create!(country_name: "GIBRALTAR", curr_name: "Gibraltar Pound", iso: "GIP")
Intdb.create!(country_name: "GREECE", curr_name: "Euro", iso: "EUR")
Intdb.create!(country_name: "GREENLAND", curr_name: "Danish Krone", iso: "DKK")
Intdb.create!(country_name: "GRENADA", curr_name: "East Caribbean Dollar", iso: "XCD")
Intdb.create!(country_name: "GUADELOUPE", curr_name: "Euro", iso: "EUR")
Intdb.create!(country_name: "GUAM", curr_name: "US Dollar", iso: "USD")
Intdb.create!(country_name: "GUATEMALA", curr_name: "Quetzal", iso: "GTQ")
Intdb.create!(country_name: "GUERNSEY", curr_name: "Pound Sterling", iso: "GBP")
Intdb.create!(country_name: "GUINEA", curr_name: "Guinea Franc", iso: "GNF")
Intdb.create!(country_name: "GUINEA-BISSAU", curr_name: "CFA Franc BCEAO", iso: "XOF")
Intdb.create!(country_name: "GUYANA", curr_name: "Guyana Dollar", iso: "GYD")
Intdb.create!(country_name: "HAITI", curr_name: "Gourde", iso: "HTG")
Intdb.create!(country_name: "HAITI", curr_name: "US Dollar", iso: "USD")
Intdb.create!(country_name: "HEARD ISLAND AND McDONALD ISLANDS", curr_name: "Australian Dollar", iso: "AUD")
Intdb.create!(country_name: "HOLY SEE (THE)", curr_name: "Euro", iso: "EUR")
Intdb.create!(country_name: "HONDURAS", curr_name: "Lempira", iso: "HNL")
Intdb.create!(country_name: "HONG KONG", curr_name: "Hong Kong Dollar", iso: "HKD")
Intdb.create!(country_name: "HUNGARY", curr_name: "Forint", iso: "HUF")
Intdb.create!(country_name: "ICELAND", curr_name: "Iceland Krona", iso: "ISK")
Intdb.create!(country_name: "INDIA", curr_name: "Indian Rupee", iso: "INR")
Intdb.create!(country_name: "INDONESIA", curr_name: "Rupiah", iso: "IDR")
Intdb.create!(country_name: "INTERNATIONAL MONETARY FUND (IMF) ", curr_name: "SDR (Special Drawing Right)", iso: "XDR")
Intdb.create!(country_name: "IRAN (ISLAMIC REPUBLIC OF)", curr_name: "Iranian Rial", iso: "IRR")
Intdb.create!(country_name: "IRAQ", curr_name: "Iraqi Dinar", iso: "IQD")
Intdb.create!(country_name: "IRELAND", curr_name: "Euro", iso: "EUR")
Intdb.create!(country_name: "ISLE OF MAN", curr_name: "Pound Sterling", iso: "GBP")
Intdb.create!(country_name: "ISRAEL", curr_name: "New Israeli Sheqel", iso: "ILS")
Intdb.create!(country_name: "ITALY", curr_name: "Euro", iso: "EUR")
Intdb.create!(country_name: "JAMAICA", curr_name: "Jamaican Dollar", iso: "JMD")
Intdb.create!(country_name: "JAPAN", curr_name: "Yen", iso: "JPY")
Intdb.create!(country_name: "JERSEY", curr_name: "Pound Sterling", iso: "GBP")
Intdb.create!(country_name: "JORDAN", curr_name: "Jordanian Dinar", iso: "JOD")
Intdb.create!(country_name: "KAZAKHSTAN", curr_name: "Tenge", iso: "KZT")
Intdb.create!(country_name: "KENYA", curr_name: "Kenyan Shilling", iso: "KES")
Intdb.create!(country_name: "KIRIBATI", curr_name: "Australian Dollar", iso: "AUD")
Intdb.create!(country_name: "KOREA (THE DEMOCRATIC PEOPLE’S REPUBLIC OF)", curr_name: "North Korean Won", iso: "KPW")
Intdb.create!(country_name: "KOREA (THE REPUBLIC OF)", curr_name: "Won", iso: "KRW")
Intdb.create!(country_name: "KUWAIT", curr_name: "Kuwaiti Dinar", iso: "KWD")
Intdb.create!(country_name: "KYRGYZSTAN", curr_name: "Som", iso: "KGS")
Intdb.create!(country_name: "LAO PEOPLE’S DEMOCRATIC REPUBLIC (THE)", curr_name: "Kip", iso: "LAK")
Intdb.create!(country_name: "LATVIA", curr_name: "Euro", iso: "EUR")
Intdb.create!(country_name: "LEBANON", curr_name: "Lebanese Pound", iso: "LBP")
Intdb.create!(country_name: "LESOTHO", curr_name: "Loti", iso: "LSL")
Intdb.create!(country_name: "LESOTHO", curr_name: "Rand", iso: "ZAR")
Intdb.create!(country_name: "LIBERIA", curr_name: "Liberian Dollar", iso: "LRD")
Intdb.create!(country_name: "LIBYA", curr_name: "Libyan Dinar", iso: "LYD")
Intdb.create!(country_name: "LIECHTENSTEIN", curr_name: "Swiss Franc", iso: "CHF")
Intdb.create!(country_name: "LITHUANIA", curr_name: "Euro", iso: "EUR")
Intdb.create!(country_name: "LUXEMBOURG", curr_name: "Euro", iso: "EUR")
Intdb.create!(country_name: "MACAO", curr_name: "Pataca", iso: "MOP")
Intdb.create!(country_name: "MACEDONIA (THE FORMER YUGOSLAV REPUBLIC OF)", curr_name: "Denar", iso: "MKD")
Intdb.create!(country_name: "MADAGASCAR", curr_name: "Malagasy Ariary", iso: "MGA")
Intdb.create!(country_name: "MALAWI", curr_name: "Malawi Kwacha", iso: "MWK")
Intdb.create!(country_name: "MALAYSIA", curr_name: "Malaysian Ringgit", iso: "MYR")
Intdb.create!(country_name: "MALDIVES", curr_name: "Rufiyaa", iso: "MVR")
Intdb.create!(country_name: "MALI", curr_name: "CFA Franc BCEAO", iso: "XOF")
Intdb.create!(country_name: "MALTA", curr_name: "Euro", iso: "EUR")
Intdb.create!(country_name: "MARSHALL ISLANDS (THE)", curr_name: "US Dollar", iso: "USD")
Intdb.create!(country_name: "MARTINIQUE", curr_name: "Euro", iso: "EUR")
Intdb.create!(country_name: "MAURITANIA", curr_name: "Ouguiya", iso: "MRO")
Intdb.create!(country_name: "MAURITIUS", curr_name: "Mauritius Rupee", iso: "MUR")
Intdb.create!(country_name: "MAYOTTE", curr_name: "Euro", iso: "EUR")
Intdb.create!(country_name: "MEMBER COUNTRIES OF THE AFRICAN DEVELOPMENT BANK GROUP", curr_name: "ADB Unit of Account", iso: "XUA")
Intdb.create!(country_name: "MEXICO", curr_name: "Mexican Peso", iso: "MXN")
Intdb.create!(country_name: "MEXICO", curr_name: "Mexican Unidad de Inversion (UDI)", iso: "MXV")
Intdb.create!(country_name: "MICRONESIA (FEDERATED STATES OF)", curr_name: "US Dollar", iso: "USD")
Intdb.create!(country_name: "MOLDOVA (THE REPUBLIC OF)", curr_name: "Moldovan Leu", iso: "MDL")
Intdb.create!(country_name: "MONACO", curr_name: "Euro", iso: "EUR")
Intdb.create!(country_name: "MONGOLIA", curr_name: "Tugrik", iso: "MNT")
Intdb.create!(country_name: "MONTENEGRO", curr_name: "Euro", iso: "EUR")
Intdb.create!(country_name: "MONTSERRAT", curr_name: "East Caribbean Dollar", iso: "XCD")
Intdb.create!(country_name: "MOROCCO", curr_name: "Moroccan Dirham", iso: "MAD")
Intdb.create!(country_name: "MOZAMBIQUE", curr_name: "Mozambique Metical", iso: "MZN")
Intdb.create!(country_name: "MYANMAR", curr_name: "Kyat", iso: "MMK")
Intdb.create!(country_name: "NAMIBIA", curr_name: "Namibia Dollar", iso: "NAD")
Intdb.create!(country_name: "NAMIBIA", curr_name: "Rand", iso: "ZAR")
Intdb.create!(country_name: "NAURU", curr_name: "Australian Dollar", iso: "AUD")
Intdb.create!(country_name: "NEPAL", curr_name: "Nepalese Rupee", iso: "NPR")
Intdb.create!(country_name: "NETHERLANDS (THE)", curr_name: "Euro", iso: "EUR")
Intdb.create!(country_name: "NEW CALEDONIA", curr_name: "CFP Franc", iso: "XPF")
Intdb.create!(country_name: "NEW ZEALAND", curr_name: "New Zealand Dollar", iso: "NZD")
Intdb.create!(country_name: "NICARAGUA", curr_name: "Cordoba Oro", iso: "NIO")
Intdb.create!(country_name: "NIGER (THE)", curr_name: "CFA Franc BCEAO", iso: "XOF")
Intdb.create!(country_name: "NIGERIA", curr_name: "Naira", iso: "NGN")
Intdb.create!(country_name: "NIUE", curr_name: "New Zealand Dollar", iso: "NZD")
Intdb.create!(country_name: "NORFOLK ISLAND", curr_name: "Australian Dollar", iso: "AUD")
Intdb.create!(country_name: "NORTHERN MARIANA ISLANDS (THE)", curr_name: "US Dollar", iso: "USD")
Intdb.create!(country_name: "NORWAY", curr_name: "Norwegian Krone", iso: "NOK")
Intdb.create!(country_name: "OMAN", curr_name: "Rial Omani", iso: "OMR")
Intdb.create!(country_name: "PAKISTAN", curr_name: "Pakistan Rupee", iso: "PKR")
Intdb.create!(country_name: "PALAU", curr_name: "US Dollar", iso: "USD")
Intdb.create!(country_name: "PALESTINE, STATE OF", curr_name: "No universal currency") 
Intdb.create!(country_name: "PANAMA", curr_name: "Balboa", iso: "PAB")
Intdb.create!(country_name: "PANAMA", curr_name: "US Dollar", iso: "USD")
Intdb.create!(country_name: "PAPUA NEW GUINEA", curr_name: "Kina", iso: "PGK")
Intdb.create!(country_name: "PARAGUAY", curr_name: "Guarani", iso: "PYG")
Intdb.create!(country_name: "PERU", curr_name: "Sol", iso: "PEN")
Intdb.create!(country_name: "PHILIPPINES (THE)", curr_name: "Philippine Peso", iso: "PHP")
Intdb.create!(country_name: "PITCAIRN", curr_name: "New Zealand Dollar", iso: "NZD")
Intdb.create!(country_name: "POLAND", curr_name: "Zloty", iso: "PLN")
Intdb.create!(country_name: "PORTUGAL", curr_name: "Euro", iso: "EUR")
Intdb.create!(country_name: "PUERTO RICO", curr_name: "US Dollar", iso: "USD")
Intdb.create!(country_name: "QATAR", curr_name: "Qatari Rial", iso: "QAR")
Intdb.create!(country_name: "RÉUNION", curr_name: "Euro", iso: "EUR")
Intdb.create!(country_name: "ROMANIA", curr_name: "Romanian Leu", iso: "RON")
Intdb.create!(country_name: "RUSSIAN FEDERATION (THE)", curr_name: "Russian Ruble", iso: "RUB")
Intdb.create!(country_name: "RWANDA", curr_name: "Rwanda Franc", iso: "RWF")
Intdb.create!(country_name: "SAINT BARTHÉLEMY", curr_name: "Euro", iso: "EUR")
Intdb.create!(country_name: "SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA", curr_name: "Saint Helena Pound", iso: "SHP")
Intdb.create!(country_name: "SAINT KITTS AND NEVIS", curr_name: "East Caribbean Dollar", iso: "XCD")
Intdb.create!(country_name: "SAINT LUCIA", curr_name: "East Caribbean Dollar", iso: "XCD")
Intdb.create!(country_name: "SAINT MARTIN (FRENCH PART)", curr_name: "Euro", iso: "EUR")
Intdb.create!(country_name: "SAINT PIERRE AND MIQUELON", curr_name: "Euro", iso: "EUR")
Intdb.create!(country_name: "SAINT VINCENT AND THE GRENADINES", curr_name: "East Caribbean Dollar", iso: "XCD")
Intdb.create!(country_name: "SAMOA", curr_name: "Tala", iso: "WST")
Intdb.create!(country_name: "SAN MARINO", curr_name: "Euro", iso: "EUR")
Intdb.create!(country_name: "SAO TOME AND PRINCIPE", curr_name: "Dobra", iso: "STD")
Intdb.create!(country_name: "SAUDI ARABIA", curr_name: "Saudi Riyal", iso: "SAR")
Intdb.create!(country_name: "SENEGAL", curr_name: "CFA Franc BCEAO", iso: "XOF")
Intdb.create!(country_name: "SERBIA", curr_name: "Serbian Dinar", iso: "RSD")
Intdb.create!(country_name: "SEYCHELLES", curr_name: "Seychelles Rupee", iso: "SCR")
Intdb.create!(country_name: "SIERRA LEONE", curr_name: "Leone", iso: "SLL")
Intdb.create!(country_name: "SINGAPORE", curr_name: "Singapore Dollar", iso: "SGD")
Intdb.create!(country_name: "SINT MAARTEN (DUTCH PART)", curr_name: "Netherlands Antillean Guilder", iso: "ANG")
Intdb.create!(country_name: "SISTEMA UNITARIO DE COMPENSACION REGIONAL DE PAGOS", curr_name: "Sucre", iso: "XSU")
Intdb.create!(country_name: "SLOVAKIA", curr_name: "Euro", iso: "EUR")
Intdb.create!(country_name: "SLOVENIA", curr_name: "Euro", iso: "EUR")
Intdb.create!(country_name: "SOLOMON ISLANDS", curr_name: "Solomon Islands Dollar", iso: "SBD")
Intdb.create!(country_name: "SOMALIA", curr_name: "Somali Shilling", iso: "SOS")
Intdb.create!(country_name: "SOUTH AFRICA", curr_name: "Rand", iso: "ZAR")
Intdb.create!(country_name: "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS", curr_name: "No universal currency") 
Intdb.create!(country_name: "SOUTH SUDAN", curr_name: "South Sudanese Pound", iso: "SSP")
Intdb.create!(country_name: "SPAIN", curr_name: "Euro", iso: "EUR")
Intdb.create!(country_name: "SRI LANKA", curr_name: "Sri Lanka Rupee", iso: "LKR")
Intdb.create!(country_name: "SUDAN (THE)", curr_name: "Sudanese Pound", iso: "SDG")
Intdb.create!(country_name: "SURINAME", curr_name: "Surinam Dollar", iso: "SRD")
Intdb.create!(country_name: "SVALBARD AND JAN MAYEN", curr_name: "Norwegian Krone", iso: "NOK")
Intdb.create!(country_name: "SWAZILAND", curr_name: "Lilangeni", iso: "SZL")
Intdb.create!(country_name: "SWEDEN", curr_name: "Swedish Krona", iso: "SEK")
Intdb.create!(country_name: "SWITZERLAND", curr_name: "Swiss Franc", iso: "CHF")
Intdb.create!(country_name: "SWITZERLAND", curr_name: "WIR Euro", iso: "CHE")
Intdb.create!(country_name: "SWITZERLAND", curr_name: "WIR Franc", iso: "CHW")
Intdb.create!(country_name: "SYRIAN ARAB REPUBLIC", curr_name: "Syrian Pound", iso: "SYP")
Intdb.create!(country_name: "TAIWAN (PROVINCE OF CHINA)", curr_name: "New Taiwan Dollar", iso: "TWD")
Intdb.create!(country_name: "TAJIKISTAN", curr_name: "Somoni", iso: "TJS")
Intdb.create!(country_name: "TANZANIA, UNITED REPUBLIC OF", curr_name: "Tanzanian Shilling", iso: "TZS")
Intdb.create!(country_name: "THAILAND", curr_name: "Baht", iso: "THB")
Intdb.create!(country_name: "TIMOR-LESTE", curr_name: "US Dollar", iso: "USD")
Intdb.create!(country_name: "TOGO", curr_name: "CFA Franc BCEAO", iso: "XOF")
Intdb.create!(country_name: "TOKELAU", curr_name: "New Zealand Dollar", iso: "NZD")
Intdb.create!(country_name: "TONGA", curr_name: "Pa’anga", iso: "TOP")
Intdb.create!(country_name: "TRINIDAD AND TOBAGO", curr_name: "Trinidad and Tobago Dollar", iso: "TTD")
Intdb.create!(country_name: "TUNISIA", curr_name: "Tunisian Dinar", iso: "TND")
Intdb.create!(country_name: "TURKEY", curr_name: "Turkish Lira", iso: "TRY")
Intdb.create!(country_name: "TURKMENISTAN", curr_name: "Turkmenistan New Manat", iso: "TMT")
Intdb.create!(country_name: "TURKS AND CAICOS ISLANDS (THE)", curr_name: "US Dollar", iso: "USD")
Intdb.create!(country_name: "TUVALU", curr_name: "Australian Dollar", iso: "AUD")
Intdb.create!(country_name: "UGANDA", curr_name: "Uganda Shilling", iso: "UGX")
Intdb.create!(country_name: "UKRAINE", curr_name: "Hryvnia", iso: "UAH")
Intdb.create!(country_name: "UNITED ARAB EMIRATES (THE)", curr_name: "UAE Dirham", iso: "AED")
Intdb.create!(country_name: "UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND (THE)", curr_name: "Pound Sterling", iso: "GBP")
Intdb.create!(country_name: "UNITED STATES MINOR OUTLYING ISLANDS (THE)", curr_name: "US Dollar", iso: "USD")
Intdb.create!(country_name: "UNITED STATES OF AMERICA (THE)", curr_name: "US Dollar", iso: "USD")
Intdb.create!(country_name: "UNITED STATES OF AMERICA (THE)", curr_name: "US Dollar (Next day)", iso: "USN")
Intdb.create!(country_name: "URUGUAY", curr_name: "Peso Uruguayo", iso: "UYU")
Intdb.create!(country_name: "URUGUAY", curr_name: "Uruguay Peso en Unidades Indexadas (URUIURUI)", iso: "UYI")
Intdb.create!(country_name: "UZBEKISTAN", curr_name: "Uzbekistan Sum", iso: "UZS")
Intdb.create!(country_name: "VANUATU", curr_name: "Vatu", iso: "VUV")
Intdb.create!(country_name: "VENEZUELA (BOLIVARIAN REPUBLIC OF)", curr_name: "Bolívar", iso: "VEF")
Intdb.create!(country_name: "VIET NAM", curr_name: "Dong", iso: "VND")
Intdb.create!(country_name: "VIRGIN ISLANDS (BRITISH)", curr_name: "US Dollar", iso: "USD")
Intdb.create!(country_name: "VIRGIN ISLANDS (U.S.)", curr_name: "US Dollar", iso: "USD")
Intdb.create!(country_name: "WALLIS AND FUTUNA", curr_name: "CFP Franc", iso: "XPF")
Intdb.create!(country_name: "WESTERN SAHARA", curr_name: "Moroccan Dirham", iso: "MAD")
Intdb.create!(country_name: "YEMEN", curr_name: "Yemeni Rial", iso: "YER")
Intdb.create!(country_name: "ZAMBIA", curr_name: "Zambian Kwacha", iso: "ZMW")
Intdb.create!(country_name: "ZIMBABWE", curr_name: "Zimbabwe Dollar", iso: "ZWL")
Intdb.create!(country_name: "ZZ01_Bond Markets Unit European_EURCO", curr_name: "Bond Markets Unit European Composite Unit (EURCO)", iso: "XBA")
Intdb.create!(country_name: "ZZ02_Bond Markets Unit European_EMU-6", curr_name: "Bond Markets Unit European Monetary Unit (E.M.U.-6)", iso: "XBB")
Intdb.create!(country_name: "ZZ03_Bond Markets Unit European_EUA-9", curr_name: "Bond Markets Unit European Unit of Account 9 (E.U.A.-9)", iso: "XBC")
Intdb.create!(country_name: "ZZ04_Bond Markets Unit European_EUA-17", curr_name: "Bond Markets Unit European Unit of Account 17 (E.U.A.-17)", iso: "XBD")
Intdb.create!(country_name: "ZZ06_Testing_Code", curr_name: "Codes specifically reserved for testing purposes", iso: "XTS")
Intdb.create!(country_name: "ZZ07_No_Currency", curr_name: "The codes assigned for transactions where no currency is involved", iso: "XXX")
Intdb.create!(country_name: "ZZ08_Gold", curr_name: "Gold", iso: "XAU")
Intdb.create!(country_name: "ZZ09_Palladium", curr_name: "Palladium", iso: "XPD")
Intdb.create!(country_name: "ZZ10_Platinum", curr_name: "Platinum", iso: "XPT")
Intdb.create!(country_name: "ZZ11_Silver", curr_name: "Silver", iso: "XAG")
