Usadb.create!(base_country: "USA", base_state_abbr: "AL", base_state: "Alabama", base_tip: 0.164) 
Usadb.create!(base_country: "USA", base_state_abbr: "AK", base_state: "Alaska", base_tip: 0.17) 
Usadb.create!(base_country: "USA", base_state_abbr: "AZ", base_state: "Arizona", base_tip: 0.165) 
Usadb.create!(base_country: "USA", base_state_abbr: "AR", base_state: "Arkansas", base_tip: 0.169) 
Usadb.create!(base_country: "USA", base_state_abbr: "CA", base_state: "California", base_tip: 0.155)
Usadb.create!(base_country: "USA", base_state_abbr: "CO", base_state: "Colorado", base_tip: 0.165) 
Usadb.create!(base_country: "USA", base_state_abbr: "CT", base_state: "Connecticut", base_tip: 0.156)
Usadb.create!(base_country: "USA", base_state_abbr: "DE", base_state: "Delaware", base_tip: 0.14)
Usadb.create!(base_country: "USA", base_state_abbr: "FL", base_state: "Florida", base_tip: 0.162)
Usadb.create!(base_country: "USA", base_state_abbr: "GA", base_state: "Georgia", base_tip: 0.162) 
Usadb.create!(base_country: "USA", base_state_abbr: "HI", base_state: "Hawaii", base_tip: 0.151) 
Usadb.create!(base_country: "USA", base_state_abbr: "ID", base_state: "Idaho", base_tip: 0.165) 
Usadb.create!(base_country: "USA", base_state_abbr: "IL", base_state: "Illinois", base_tip: 0.165) 
Usadb.create!(base_country: "USA", base_state_abbr: "IN", base_state: "Indiana", base_tip: 0.164) 
Usadb.create!(base_country: "USA", base_state_abbr: "IA", base_state: "Iowa", base_tip: 0.161) 
Usadb.create!(base_country: "USA", base_state_abbr: "KS", base_state: "Kansas", base_tip: 0.162) 
Usadb.create!(base_country: "USA", base_state_abbr: "KY", base_state: "Kentucky", base_tip: 0.164) 
Usadb.create!(base_country: "USA", base_state_abbr: "LA", base_state: "Louisiana", base_tip: 0.161) 
Usadb.create!(base_country: "USA", base_state_abbr: "ME", base_state: "Maine", base_tip: 0.164) 
Usadb.create!(base_country: "USA", base_state_abbr: "MD", base_state: "Maryland", base_tip: 0.158) 
Usadb.create!(base_country: "USA", base_state_abbr: "MA", base_state: "Massachusetts", base_tip: 0.157) 
Usadb.create!(base_country: "USA", base_state_abbr: "MI", base_state: "Michigan", base_tip: 0.164) 
Usadb.create!(base_country: "USA", base_state_abbr: "MN", base_state: "Minnesota", base_tip: 0.157) 
Usadb.create!(base_country: "USA", base_state_abbr: "MS", base_state: "Mississippi", base_tip: 0.165) 
Usadb.create!(base_country: "USA", base_state_abbr: "MO", base_state: "Missouri", base_tip: 0.165) 
Usadb.create!(base_country: "USA", base_state_abbr: "MT", base_state: "Montana", base_tip: 0.16) 
Usadb.create!(base_country: "USA", base_state_abbr: "NE", base_state: "Nebraska", base_tip: 0.155) 
Usadb.create!(base_country: "USA", base_state_abbr: "NV", base_state: "Nevada", base_tip: 0.162) 
Usadb.create!(base_country: "USA", base_state_abbr: "NH", base_state: "New Hampshire", base_tip: 0.162) 
Usadb.create!(base_country: "USA", base_state_abbr: "NJ", base_state: "New Jersey", base_tip: 0.161) 
Usadb.create!(base_country: "USA", base_state_abbr: "NM", base_state: "New Mexico", base_tip: 0.166) 
Usadb.create!(base_country: "USA", base_state_abbr: "NY", base_state: "New York", base_tip: 0.158) 
Usadb.create!(base_country: "USA", base_state_abbr: "NC", base_state: "North Carolina", base_tip: 0.167) 
Usadb.create!(base_country: "USA", base_state_abbr: "ND", base_state: "North Dakota", base_tip: 0.156) 
Usadb.create!(base_country: "USA", base_state_abbr: "OH", base_state: "Ohio", base_tip: 0.161) 
Usadb.create!(base_country: "USA", base_state_abbr: "OK", base_state: "Oklahoma", base_tip: 0.162) 
Usadb.create!(base_country: "USA", base_state_abbr: "OR", base_state: "Oregon", base_tip: 0.157) 
Usadb.create!(base_country: "USA", base_state_abbr: "PA", base_state: "Pennsylvania", base_tip: 0.16) 
Usadb.create!(base_country: "USA", base_state_abbr: "RI", base_state: "Rhode Island", base_tip: 0.158) 
Usadb.create!(base_country: "USA", base_state_abbr: "SC", base_state: "South Carolina", base_tip: 0.167) 
Usadb.create!(base_country: "USA", base_state_abbr: "SD", base_state: "South Dakota", base_tip: 0.153) 
Usadb.create!(base_country: "USA", base_state_abbr: "TN", base_state: "Tennessee", base_tip: 0.163) 
Usadb.create!(base_country: "USA", base_state_abbr: "TX", base_state: "Texas", base_tip: 0.163) 
Usadb.create!(base_country: "USA", base_state_abbr: "UT", base_state: "Utah", base_tip: 0.161) 
Usadb.create!(base_country: "USA", base_state_abbr: "VT", base_state: "Vermont", base_tip: 0.155) 
Usadb.create!(base_country: "USA", base_state_abbr: "VA", base_state: "Virginia", base_tip: 0.16) 
Usadb.create!(base_country: "USA", base_state_abbr: "WA", base_state: "Washington", base_tip: 0.159) 
Usadb.create!(base_country: "USA", base_state_abbr: "WV", base_state: "West Virginia", base_tip: 0.167) 
Usadb.create!(base_country: "USA", base_state_abbr: "WI", base_state: "Wisconsin", base_tip: 0.159) 
Usadb.create!(base_country: "USA", base_state_abbr: "WY", base_state: "Wyoming", base_tip: 0.154) 


Service.create!(general_service: "Good Service", service_tip_overide: 0.20)
Service.create!(general_service: "Normal Service")	
Service.create!(general_service: "Poor Service", service_tip_overide: 0.10)
Service.create!(general_service: "Horrible Service",service_tip_overide: 0.1)


